### ISSUE TITLE
Getting error 53000

### ISSUE THREAD

**Issue by benacler** [TwilioDevEd/voice-javascript-sdk-quickstart-node#108]
Getting error on device.register() using the same code. no way to have it working. How to debug the error ?

**Comment by bld010** [comment]
Hi @benacler 

I would first make sure that frontend is receiving the access token. Can you console.log the access token immediately before you instantiate the device? 

Next, are you seeing any other errors in your browser console? (Other than the 53000 from Twilio?) If you could post a screenshot here, that may help me debug this.

**Comment by benacler** [comment]
I found the error, I had my entire account default to a different zone (Ireland). I think you should somehow report a sensate error when this happens. I'll still struggling with recording not working once switching the TwiML on IE1, and even in this case and with the support of one of your internals, things are going too slow... thanks btw you can close this issue
