### ISSUE TITLE
ConnectionError: ConnectionError (53000): Raised whenever a signaling connection error occurs that is not covered by a more specific error code.

### ISSUE THREAD

**Issue by michaelsync** [TwilioDevEd/voice-javascript-sdk-quickstart-node#113]
I am getting this error when I run. 

ConnectionError: ConnectionError (53000): Raised whenever a signaling connection error occurs that is not covered by a more specific error code.

Twilio Nuget: 5.75.0
/*! @twilio/voice-sdk.js 2.1.1

![image](https://user-images.githubusercontent.com/192911/168441068-68748bf4-2067-4e25-9e67-c27ccf2fcfae.png)

**Comment by michaelsync** [comment]
Sorry. I have opened the same ticket in .NET https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-csharp/issues/2

**Comment by bld010** [comment]
No worries! Closing this duplicate issue.
