### ISSUE TITLE
Getting ConnectionError (53000)

### ISSUE THREAD

**Issue by smali-kazmi** [TwilioDevEd/voice-javascript-sdk-quickstart-node#250]
I am getting I had go through the pervious errors and confirm all configs are as expected but I am still getting this error on both this v1 an v2 version of twilio

<img width="1437" alt="image" src="https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node/assets/749977/b2efdf17-a52c-4052-b657-62ee06d9f8f8">

**Comment by smali-kazmi** [comment]
when force edge to us1 then error was changed and getting this error 
<img width="1414" alt="image" src="https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node/assets/749977/7c4bcb4e-a6d9-4d3c-9f37-a1c179065b06">

**Comment by Utakato** [comment]
Same here, did you manage to find a solution?
<img width="975" alt="image" src="https://github.com/user-attachments/assets/2eb69dde-265d-497c-a8b6-751462df1dce">

**Comment by bld010** [comment]
Hi there! I'm not able to reproduce this error.  

For these types of errors, there are two things we recommend: 

1. Start by going into your Twilio Console and [check your Error Logs](https://console.twilio.com/us1/monitor/logs/debugger/errors). 
2. Decode your Access Token on [jwt.io](https://jwt.io). Make sure all of the expected information is present. The docs page on Access Tokens has more information. In particular, you should read the [Token anatomy section](https://www.twilio.com/docs/iam/access-tokens#token-anatomy) and the [Create an Access Token for the Voice SDKs section](https://www.twilio.com/docs/iam/access-tokens#create-an-access-token-for-the-voice-sdks). 

If you are attempting to use a region other than US1, there are several steps you need to follow. Check out the [Global Infrastructure docs](https://www.twilio.com/docs/global-infrastructure/use-the-programmable-voice-javascript-sdk-with-a-non-us-twilio-region) for more information. 

If you're still having this issue after following the steps above, please open a new issue and include: 
- any errors you find in the Error Logs
- A screenshot of your TwiML App page in the Console with any sensitive information redacted
- A screenshot of any errors on your ngrok server
