### ISSUE TITLE
Gets disconnect while uploaded to server

### ISSUE THREAD

**Issue by shirishpokharel** [TwilioDevEd/voice-javascript-sdk-quickstart-node#70]
![image](https://user-images.githubusercontent.com/36003463/148787067-630e5f7b-ca78-4228-af08-c5221e1961c0.png)

The whole app runs smoothly in the localhost. But after deploying to server, it gets disconnected whenever I try making a call with the username. 

Don't know what is happening here as i couldn't figure out what the issue is. I have also given the endpoint in the twilio. Is it something with that ?

![image](https://user-images.githubusercontent.com/36003463/148787384-2e49cce7-d2b6-4076-8250-9c8c139bc700.png)

**Comment by bld010** [comment]
Hi there. Can you tell me a little more about what you mean by "Try making a call with the username"?

Are you seeing any errors in your [Twilio Console](https://console.twilio.com/)? (Log in and go to the **Monitor** tab in the left navigation pane)
